export const requestBody = {
    "query[paginate]": "infinity",
    "query[show_label]": "1מתוך11",
    "query[next_page_link]": "https",
    "query[query_vars][tag]": "%d7%92%d7%9c-%d7%94%d7%98%d7%a8%d7%95%d7%a8",
    "query[query_vars][tag_id]": "136",
    "query[query_vars][paged]": "1",
    "query[query_vars][tag_slug__in][]": "%d7%92%d7%9c-%d7%94%d7%98%d7%a8%d7%95%d7%a8",
    "query[query_vars][post_type]": "any",
    "query[query_vars][posts_per_page]": "5",
    "query[query_vars][lazy_load_term_meta]": "1",
    "query[query_vars][order]": "DESC",
    "query[show_excerpt]": "0",
    "query[_layout][state]": "1|1|0",
    "query[_layout][page]": "2-col-right",
    "type": "custom",
    "view": "Publisher::bs_pagin_ajax_archive",
    "current_page": "1",
    "ajax_url": "/wp-admin/admin-ajax.php",
    "remove_duplicates": "0",
    "paginate": "infinity",
    "_layout[state]": "1|1|0",
    "_layout[page]": "2-col-right",
    "action": "pagination_ajax",
    "pagin_type": "infinity",
}